namespace Core {
    enum _LIB_CORE_ExType {
        // These must be kept in sync with CoreExceptionTypes in Constants.cry in the interpreter.
        FATAL = 0,
        GENERIC_EXCEPTION = 1,
        ASSERTION_FAILED = 2,
        DIVISION_BY_ZERO = 3,
        INDEX_OUT_OF_RANGE = 4,
        INVALID_ARGUMENT = 5,
        INVALID_ASSIGNMENT = 6,
        INVALID_INVOCATION = 7,
        INVALID_KEY = 8,
        KEY_NOT_FOUND = 9,
        NULL_REFERENCE = 10,
        UNASSIGNED_VARIABLE = 11,
        UNKNOWN_FIELD = 12,
        UNSUPPORTED_OPERATION = 13,
    }

    /*
        When there are VM-generated exceptions (as opposed to exceptions thrown directly from code with the
        throw keyword) the easiest way to go about this is to simply treat it as a function invocation to this
        particular function which itself just uses the throw keyword.
    */
    function _LIB_CORE_generateException(type, message) {
        switch (type) {
            case _LIB_CORE_ExType.FATAL: throw new FatalException(message);
            case _LIB_CORE_ExType.ASSERTION_FAILED: throw new AssertionFailedException(message);
            case _LIB_CORE_ExType.DIVISION_BY_ZERO: throw new DivisionByZeroException(message);
            case _LIB_CORE_ExType.INDEX_OUT_OF_RANGE: throw new IndexOutOfRangeException(message);
            case _LIB_CORE_ExType.INVALID_ARGUMENT: throw new InvalidArgumentException(message);
            case _LIB_CORE_ExType.INVALID_ASSIGNMENT: throw new InvalidAssignmentException(message);
            case _LIB_CORE_ExType.INVALID_INVOCATION: throw new InvalidInvocationException(message);
            case _LIB_CORE_ExType.INVALID_KEY: throw new InvalidKeyException(message);
            case _LIB_CORE_ExType.KEY_NOT_FOUND: throw new KeyNotFoundException(message);
            case _LIB_CORE_ExType.NULL_REFERENCE: throw new NullReferenceException(message);
            case _LIB_CORE_ExType.UNASSIGNED_VARIABLE: throw new UnassignedVariableException(message);
            case _LIB_CORE_ExType.UNKNOWN_FIELD: throw new UnknownFieldException(message);
            case _LIB_CORE_ExType.UNSUPPORTED_OPERATION: throw new UnsupportedOperationException(message);
            default: throw new Exception(message);
        }
    }

    class Exception {
        /*
            nativeData[0] -> (boolean) is fatal exception?
            nativeData[1] -> (List<int>) list of PC's this exception bubbles through
                PC trace is only set when throw is invoked.
        */

        // Do not re-order these.
        // .message field position within the class is assumed at compile time.
        field cause;
        field message;

        constructor(message = null, cause = null) {
            $$$('allocNativeData', this, 2);
            $$$('setNativeData', this, 0, false); // is fatal?
            this.message = message;
            this.cause = cause;
        }

        function getTrace() {
            return $$$('getExceptionTrace', this);
        }
    }

    class FatalException : Exception {
        constructor(m = null, c = null) : base(m, c) {
            $$$('setNativeData', this, 0, true); // is fatal?
        }
    }

    class AssertionFailedException : Exception { constructor(m = null, c = null) : base(m, c) { } }
    class DivisionByZeroException : Exception { constructor(m = null, c = null) : base(m, c) { } }
    class IndexOutOfRangeException : Exception { constructor(m = null, c = null) : base(m, c) { } }
    class InvalidArgumentException : Exception { constructor(m = null, c = null) : base(m, c) { } }
    class InvalidAssignmentException : Exception { constructor(m = null, c = null) : base(m, c) { } }
    class InvalidInvocationException : Exception { constructor(m = null, c = null) : base(m, c) { } }
    class InvalidKeyException : Exception { constructor(m = null, c = null) : base(m, c) { } }
    class InvalidOperationException : Exception { constructor(m = null, c = null) : base(m, c) { } }
    class KeyNotFoundException : Exception { constructor(m = null, c = null) : base(m, c) { } }
    class NotImplementedException : Exception { constructor(m = null, c = null) : base(m, c) { } }
    class NullReferenceException : Exception { constructor(m = null, c = null) : base(m, c) { } }
    class UnassignedVariableException : Exception { constructor(m = null, c = null) : base(m, c) { } }
    class UnknownFieldException : Exception { constructor(m = null, c = null) : base(m, c) { } }
    class UnsupportedOperationException : Exception { constructor(m = null, c = null) : base(m, c) { } }
}
